### ISSUE TITLE
error report

### ISSUE THREAD

**Issue by HGT-UwU** [lcmmichielsen/hierarchicalprogressivelearning#3]
y_pred1 = predict.predict_labels(x_test, tree1) 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\*\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\scHPL\predict.py", line 107, in predict_labels
    label, score = _predict_node(testpoint, n, dimred)
  File "C:\Users\*\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\scHPL\predict.py", line 144, in _predict_node
    if pcs:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Comment by lcmmichielsen** [comment]
Fixed the error and updated the packages in the pip repository
